CREATE TABLE IF NOT EXISTS SP (
			ID INTEGER AUTO_INCREMENT,
			TENANT_ID INTEGER,
			NAME VARCHAR(254) NOT NULL,
			DISPLAY_NAME VARCHAR(255),
			DESCRIPTION VARCHAR (1024),
			IS_ENABLED CHAR(1) NOT NULL DEFAULT '1',
 			USER_CLAIM_URI VARCHAR(254),
 			ROLE_CLAIM_URI VARCHAR(254),
 			PRIMARY KEY (ID),
			UNIQUE (TENANT_ID, NAME));

CREATE TABLE IF NOT EXISTS SP_IDP_MAPPING (
			ID INTEGER AUTO_INCREMENT,
			TENANT_ID INTEGER,
			SP_ID INTEGER NOT NULL,
			IDP_ID INTEGER NOT NULL,
 			PRIMARY KEY (ID),
			UNIQUE (SP_ID, IDP_ID));

-- ALTER TABLE SP_IDP_MAPPING ADD CONSTRAINT IDP_ID_CONSTRAINT FOREIGN KEY (IDP_ID) REFERENCES IDP (ID) ON DELETE CASCADE;
ALTER TABLE SP_IDP_MAPPING ADD CONSTRAINT SP_ID_CONSTRAINT FOREIGN KEY (SP_ID) REFERENCES SP (ID) ON DELETE CASCADE;